### ISSUE TITLE
Remove Cambria Math from flavors that don't need it

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#133]
These flavors currently have Cambria Math in the XSL files:

CalConnect:
Arial, Times New Roman, Cambria Math, HanSans, Courier

IEC:
Arial, Times New Roman, Cambria Math, HanSans, Courier

ITU:
Arial, Cambria Math, Courier, Times New Roman

OGC:
Arial, Cambria Math, Courier, Times New Roman

UN:
Arial, Arial Black, Cambria Math, Courier, Times New Roman, HanSans

We want to remove Cambria Math from all these flavors because they are not necessary.

**Comment by Intelligent2013** [comment]
@ronaldtse 

> CalConnect:
> Arial, Times New Roman, Cambria Math, HanSans, Courier

Removed (In existing xml example there aren't mathml data.)

> IEC:
> Arial, Times New Roman, Cambria Math, HanSans, Courier

We can't remove Cambria Math, because it uses for math equations:
- with Cambria Math:
![image](https://user-images.githubusercontent.com/5559926/80229853-bb408300-8659-11ea-945d-55ae29fdd6c1.png)

- without Cambria Math:
![image](https://user-images.githubusercontent.com/5559926/80230033-0195e200-865a-11ea-9d52-2323dbe980b6.png)

> ITU:
> Arial, Cambria Math, Courier, Times New Roman

We can't remove Cambria Math, because it uses for math equations.

> OGC:
> Arial, Cambria Math, Courier, Times New Roman

Removed (In existing xml examples there aren't mathml data.)

> UN:
> Arial, Arial Black, Cambria Math, Courier, Times New Roman, HanSans

Removed (In existing xml examples there aren't mathml data.),

**Comment by ronaldtse** [comment]
> We can't remove Cambria Math, because it uses for math equations:

@Intelligent2013 can we use a non Cambria Math font because Linux/macOS systems don't have it by default? e.g. Can we use the other fonts like Adobe Source?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can we use a non Cambria Math font because Linux/macOS systems don't have it by default? e.g. Can we use the other fonts like Adobe Source or Arial?
> 
> The two comparisons look fine to me (Math in Arial looks fine?):
> 

Cambria Math has a math specific glyph set:

![image](https://user-images.githubusercontent.com/5559926/80239792-79b7d400-8669-11ea-88ff-125853a947ff.png)

![image](https://user-images.githubusercontent.com/5559926/80239757-6dcc1200-8669-11ea-9463-9c63afe44dd7.png)

![image](https://user-images.githubusercontent.com/5559926/80239729-673d9a80-8669-11ea-8138-d39ccbbd4223.png)

To make a decision what is another font can we use instead of Cambria Math, we need to compare a glyph sets of these fonts. I'll see how to make it programmatically.

**Comment by Intelligent2013** [comment]
From https://trac.webkit.org/wiki/MathML/Fonts:
**Recommended Math Fonts**
Here is a list of known math fonts that can be used to render MathML formulas in WebKit:

- ​Asana Math
- ​Cambria Math
- ​DejaVu Math TeX Gyre
- ​Latin Modern Math
- ​Libertinus Math
- ​Lucida Bright Math
- ​Minion Math
- ​STIX Math
- ​TeX Gyre Bonum Math
- ​TeX Gyre Pagella Math
- ​TeX Gyre Schola Math
- ​TeX Gyre Termes Math
- ​XITS Math

**Comment by ronaldtse** [comment]
@Intelligent2013 let's use STIX Math since it is freely distributable and also used in MathJax:

https://en.wikipedia.org/wiki/STIX_Fonts_project
> The javascript framework MathJax uses the STIX fonts for including mathematics in web pages. 

STIX2Math:
https://github.com/stipub/stixfonts/blob/master/OTF/STIX2Math.otf

Since it's only 800KB, we could either include it in mn2pdf or install via Fontist.

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated mn2pdf (automatically font STIX2Math installation) and removed Cambria Math from xslt. Now Cambria Math is using in ISO flavor only.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
