### ISSUE TITLE
BIPM brochure review: Big gap in unordered list

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn-native-pdf#268]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

In  Appendix 1, `16th CGPM, 1979`. There is a big gap between two unordered list items:

![issue10-generated](https://user-images.githubusercontent.com/33627611/96005415-6ad8ff80-0e0a-11eb-802a-5ba367f77912.PNG)

Original version:
![issue10-original](https://user-images.githubusercontent.com/33627611/96006786-d53e6f80-0e0b-11eb-9f27-e7b01b368182.PNG)

I'm noticing that this problem raises because there are two footnotes integrated in one list item. Let me know if approaching the markup in another way would help.

**Comment by ronaldtse** [comment]
From BIPM: 
> it does not look brilliant with the large vertical spacing between the bullet points, but I think that the advantage of machine-readability outweighs this. I imagine that in the particular case you showed, this spacing is only due to the fact that the fifth bullet point also has a side note? If this wouldn’t be the case, it could have a normal spacing with the side note of the fourth bullet point running also alongside of the fifth?  Do you have an overview how many of these excessive spacings would occur?

Response:
> Regarding question 2, the vertical spacing occurs not because of the 5th bullet — it is because we have to use a table row to align the top of the content with its annotation, in order to ensure that the reader sees the content together with the appropriate notes. For example, if a short bullet text has multiple notes, which requires more vertical height than that of the short bullet text, they will be put in the same row and cause this extraneous vertical space.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/11865/96138267-2a73a180-0f30-11eb-8f4d-d4e4484ec9ab.png">

Let me find out how many instances this occurs.

**Comment by Intelligent2013** [comment]
Some remarks regarding side notes:
- footnotes show near the concordance element
- notes, which related to concrete items, show near the concordance element
- notes, which related to list, show near first list item

I've tried to create a PDF for two-weeks old xml with list level notes instead of footnotes:
![изображение](https://user-images.githubusercontent.com/5559926/96141825-10bf6380-0f0a-11eb-8526-a8a82c31029c.png)

and as I've specified, all notes show after first list item.

**Comment by ronaldtse** [comment]
There are 5 instances of vertical spacing due to notes too close to each other:

1
<img width="618" alt="Screen Shot 2020-10-15 at 10 25 33 PM" src="https://user-images.githubusercontent.com/11865/96143078-5a717380-0f35-11eb-902a-f86555a8f995.png">

2 & 3
<img width="641" alt="Screen Shot 2020-10-15 at 10 26 39 PM" src="https://user-images.githubusercontent.com/11865/96143250-7ffe7d00-0f35-11eb-8f66-6264021051d5.png">

4
<img width="612" alt="Screen Shot 2020-10-15 at 10 27 11 PM" src="https://user-images.githubusercontent.com/11865/96143324-93114d00-0f35-11eb-80ad-2a85f997a14d.png">

5
<img width="579" alt="Screen Shot 2020-10-15 at 10 27 43 PM" src="https://user-images.githubusercontent.com/11865/96143418-a6bcb380-0f35-11eb-8998-3ca0da839d49.png">

**Comment by ronaldtse** [comment]
There are two options we can take:

1. Do not position notes according to the list items, and just flow them one by one inside a clause. We can change the notes into footnotes so the reader can link in-content asterisks (* => note 1, ** note 2…) to the correct note.

2. Accept the current drawback with vertical spacing, recognizing that there is value in having the appropriate notes right next to the content it applies to.

Awaiting BIPM feedback.

**Comment by ronaldtse** [comment]
From BIPM:

> In my opinion, the best option would be to let the side notes flow one by one inside a clause (without the extra vertical spacing) and adding asterisks to the main text and the related note. 

The concern of letting the side notes flow one by one inside a clause is when the clause is long, then there could be a vertical space difference between the location of content vs the location of the note that applies to the content.

The above may not be a concern (let us experiment), but this mechanism will somewhat change the semantics of the original SI Brochure (in Appendix 1, notes previously without asterisks will be assigned asterisks now). Would that be OK?

> Would that be possible by keeping them as side notes and not making them footnotes (at the bottom of the page)?

Of course, by “footnotes” here we mean that they are "numbered notes" (identified by asterisks, not identified by position).

What do you think @Intelligent2013 @opoudjis ?

**Comment by Intelligent2013** [comment]
I've made one experiment with moving list-item notes up to clause-level.

Before:
![изображение](https://user-images.githubusercontent.com/5559926/96302647-d33e0180-1001-11eb-8b76-754ea5778ad8.png)


After (blue line is a separator between different clauses):

![изображение](https://user-images.githubusercontent.com/5559926/96302714-e94bc200-1001-11eb-8126-72bf17804661.png)

(please don't count asterisk, they are just fixed **)

You can see that there isn't vertical space in list, but there is the gap between titles:
`SI unit of luminous intensity (candela) (CR, 100 and Metrologia, 1980, 16, 56)*` - 3rd level clause/title
and
`Resolution 3` - 4th level clause/title

We can't merge clause level 3 and clause level 4 together, because clause level can have a more lines, and then notes from clause level 4 will be positioned far above.

I would like to make one more experiment - move notes to 1-level up, i.e. from _list-item_ level to _list_ level, instead of 2-level up (as made)

**Comment by ronaldtse** [comment]
> I would like to make one more experiment - move notes to 1-level up, i.e. from list-item level to list level, instead of 2-level up (as made)

Agree, let's see how it goes!

**Comment by Intelligent2013** [comment]
Latest PDF with list-level notes:
[si-brochure-en.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/5395572/si-brochure-en.presentation.pdf)

I've moved notes to 1-level up (in xslt on fly), i.e. from list-item level to list level, It solves the issue from initial post:
![изображение](https://user-images.githubusercontent.com/5559926/96336280-50f82080-1087-11eb-99a2-202dbdb9fbb2.png)

But we still have another issues 1 & 2 from https://github.com/metanorma/mn-native-pdf/issues/268#issuecomment-709363979:
![изображение](https://user-images.githubusercontent.com/5559926/96336333-a2a0ab00-1087-11eb-9bb9-2466203c1143.png)

and 3:

![изображение](https://user-images.githubusercontent.com/5559926/96336385-1478f480-1088-11eb-8b01-c8a3ae8e8333.png)

**Comment by ronaldtse** [comment]
Communication with BIPM.

We have done two experiments on the notes in Appendix 1:

1. Number all notes (with asterisks as identifiers), free-flow the notes from the clause-level (the clause title).
2. Number all notes (with asterisks as identifiers), free-flow the notes from the list-level (“considering”…).

(Do note that there can be 8 notes inside a single resolution in the Brochure [page 54], so the 8th note becomes “********”…)

Approach 1 gives us this (left old, right new).  Notice that while the vertical gap between list items are eliminated, the note on the clause heading and the subclause heading (“Resolution 3”) remains. [NOTE: We might not want to merge these clause levels (level 3 and level 4), because a clause level can have multiple lines, and in that case the notes from clause level 4 will be positioned too high above.]

<img width="645" alt="Screen Shot 2020-10-18 at 9 51 18 PM" src="https://user-images.githubusercontent.com/11865/96371716-bafeeb80-1195-11eb-82e3-b605dce24401.png">

Approach 2 gives us this (left old, right new). In this case it looks nicer. However, issues 1, 2 and 3 in the previous instance will remain.

<img width="641" alt="Screen Shot 2020-10-18 at 9 54 56 PM" src="https://user-images.githubusercontent.com/11865/96371721-bfc39f80-1195-11eb-8e26-0a8befe94720.png">

Reminder of issues 1/2/3 (Issue 1, 2 at left; 3 at right):

<img width="649" alt="Screen Shot 2020-10-18 at 9 57 53 PM" src="https://user-images.githubusercontent.com/11865/96371725-c6521700-1195-11eb-8811-7fef16f326a4.png">

There are 3 options:

a. Keep the original semantics where the notes are positioned next to the content, so we don’t see “********” but have the 4 vertical gaps in the document.

b. Change all notes to numbered notes, free-flow them from the clause level (approach 1 above), see the “********”, and only have vertical gaps between "resolution title” and “resolution number” (Issues 1, 2 remains).

c. Change all notes to numbered notes, free-flow them from the list level (approach 2 above), see the “********”, and only have vertical gaps in 3 of the original instances (Issues 1, 2, 3 remains).

d. We can experiment more… maybe some semantic changes on clause levels 3 & 4 (as in the NOTE above)

We could also shrink the “********” into something like “Note 8” if we do b or c. 

-------

On further investigation, option (d) mentioned earlier might not be ideal for two reasons:

1. The resolution clause (e.g. “Resolution 2”) is semantically encoded independently from the theme title (e.g. "Recommended value for the speed of light”). The reason is that the cross-references directly link to the Resolution instead of the theme title (so that when the user clicks in the PDF bookmark, the page scrolls down directly to the Resolution, not the theme title).

2. If we merge the Resolution heading with the theme heading, the notes will flow from the theme heading, which may cause the notes to be concentrated higher up which can have the content and its note on separate pages. For example, in page 52, Resolution 12 spans 3 pages with 8 notes — its notes 3 and 4 will be on the first page, but the content of notes 3 and 4 are on the second page.

So far a, b, c are better options.

**Comment by ronaldtse** [comment]
Response from BIPM:

>> in Appendix 1, notes previously without asterisks will be assigned asterisks now [...] Would that be OK?
> Yes, I think so. As you write, let['s] experiment, but try to stick as closely as possibly with the original layout.

So encoding the sidebar notes as numbered notes are acceptable as long as the layout isn't altered greatly.

**Comment by Intelligent2013** [comment]
Question about issue 3.
In the current version of XML, the title `Derived units` encoded as `p`:
```xml
<p id="_cd550b39-c971-43bc-aaa8-758a6d7ec884"><strong><em>Derived units</em></strong><fn reference="8"><p id="_500c4bfc-2376-43c5-bab1-d94503443746">The 13th CGPM in 1967 (<xref target="cgpm13th1968r6r6">Resolution 6</xref>) specified other units which should be added to the list. In principle, this list of derived units is without limit.</p></fn></p>
<table id="_262f2784-afd5-401d-9a33-fb23f5e30b6b" unnumbered="true">
<tbody>
<tr>
<td valign="top" align="left">area</td>
<td valign="top" align="left">square metre</td>
```

Can we encode it in adoc as table title (but without table number) for resulted XML?:
```xml
<table id="_262f2784-afd5-401d-9a33-fb23f5e30b6b" unnumbered="true">
<name><em>Derived units</em><fn reference="8"><p id="_500c4bfc-2376-43c5-bab1-d94503443746">The 13th CGPM in 1967 (<xref target="cgpm13th1968r6r6">Resolution 6</xref>) specified other units which should be added to the list. In principle, this list of derived units is without limit.</p></fn></name>
<tbody>
<tr>
<td valign="top" align="left">area</td>
<td valign="top" align="left">square metre</td>
```

If so, then we can have this result in PDF:
![изображение](https://user-images.githubusercontent.com/5559926/96709914-04248a80-13a4-11eb-8206-2c9ef6c76bb8.png)

**Comment by Intelligent2013** [comment]
Ignore my question. In any case this is not solving the issues 1 & 2.

**Comment by Intelligent2013** [comment]
Issues fixed.

1 & 2:
![изображение](https://user-images.githubusercontent.com/5559926/96758113-09eb9180-13df-11eb-87af-8b233a1eb3e1.png)

3: 
![изображение](https://user-images.githubusercontent.com/5559926/96758246-343d4f00-13df-11eb-9363-30b46c244b73.png)

4:
![изображение](https://user-images.githubusercontent.com/5559926/96758287-428b6b00-13df-11eb-8624-64fe287aaa77.png)


Latest PDFs:
[collection.presentation.pdf](https://github.com/metanorma/mn-native-pdf/files/5417814/collection.presentation.pdf)
[collection.presentation_en.pdf](https://github.com/metanorma/mn-native-pdf/files/5417818/collection.presentation_en.pdf)
[collection.presentation_fr.pdf](https://github.com/metanorma/mn-native-pdf/files/5417819/collection.presentation_fr.pdf)

**Comment by ronaldtse** [comment]
Reported back to BIPM, consider this fixed. Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
For documentation purposes, sent to the BIPM:

> 1. In body content, notes are co-located with the content (identical to the original).

> 2. In Appendix 1, all notes are encoded as numbered notes:
> - If a note applies to the clause (theme), it is marked with an asterisk (identical to the original)
> - If a note applies to a particular location inside decision/resolution text, it is encoded as a numbered note that begins with (1). (updated from original)

> 3. All numbered notes are promoted to the top of the clause container it belongs to, so they free flow from the top of the clause.

**Comment by Intelligent2013** [comment]
Additional comment to 3.
- only if clause title has a note (asterisk)
- if clause title doesn't have a note (with asterisk), then numbered note placed near the text, for example:

![изображение](https://user-images.githubusercontent.com/5559926/96766160-56d16700-13e3-11eb-9b00-742e0c778a7b.png)


![изображение](https://user-images.githubusercontent.com/5559926/96766191-60f36580-13e3-11eb-91e6-9d52e2359544.png)

![изображение](https://user-images.githubusercontent.com/5559926/96766247-75376280-13e3-11eb-8eb3-eafe66b9bc8c.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 ! This is excellent.

**Comment by ronaldtse** [comment]
Will close this once I get BIPM confirmation.

**Comment by ronaldtse** [comment]
BIPM’s Michael Stock confirms and agrees that the latest PDF solves the problem. Closing now. Thanks!
