### ISSUE TITLE
Degrade gracefully if fonts not found

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-native-pdf#74]
The XSLT stylesheets are going to be used in arbitrary operating systems, and that means that the attempt to find the "right" font directory for fonts to use in PDF generation may fail. The stylesheets need to deal with that eventuality, and degrade gracefully if the expected fonts are not found, by still generating output with (presumably) system default fonts.

**Comment by opoudjis** [comment]
@ronaldtse FYI

**Comment by ronaldtse** [comment]
@Intelligent2013 could you please help update mn2pdf so that it degrades gracefully (using some system fonts)? Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse 
Hmm... Looks like this isn't straightforward task. We can use font substitutions mechanism in Apache FOP, for example, instead of Arial we can use Helvetica (base 14 font integrated into Apache FOP). But, from the other side, PDF should be UA compliance, and for this, we should specify existing url for Helvetica font file which doesn't exist in all OS.
I propose to distibute GNU Freefonts (https://www.gnu.org/software/freefont/index.html) with mn2pdf.jar and substitute them in case when font from config file isn't exist. It's ok?

**Comment by ronaldtse** [comment]
@Intelligent2013 how about we use Source Sans Pro/Serif/Code ? They look better.

**Comment by Intelligent2013** [comment]
@ronaldtse no problem to use Source fonts. I've checked some font and it's embedding.
My idea is _distribute_ (without 'curl' utility using) fonts with mn2pdf, which will be used for missing fonts. It guarantees that mn2pdf will produce pdf even when remote resource (fonts) isn't available.

**Comment by ronaldtse** [comment]
> My idea is distribute (without 'curl' utility using) fonts with mn2pdf, which will be used for missing fonts. It guarantees that mn2pdf will produce pdf even when remote resource (fonts) isn't available.

Agree. We are allowed to distribute these open source (Source X Pro) fonts.

There is also a problem with mn2pdf (or Apache FOP) that there's no system font detection. But I guess it's not a huge issue.

**Comment by Intelligent2013** [comment]
> There is also a problem with mn2pdf (or Apache FOP) that there's no system font detection. But I guess it's not a huge issue.
What do you mean? If you think about <auto-detect/>feature, but this option don't solve non-existing font issue. We should set 'embed-url' attribute for all used fonts for PDF/UA compliance.

**Comment by Intelligent2013** [comment]
I've added Source Pro font substitution in case if some fonts are missing.
Repository https://github.com/metanorma/mn2pdf updated.
