### ISSUE TITLE
Editor: Do OGC document review

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#89]
@metanorma/editors can you please help review the OGC PDF documents generated compared to the Word documents generated from Metanorma?

Please help split the work beforehand since there is quite a bit. Thanks!

**Comment by manuel489** [comment]
@ronaldtse , FYI, I checked the list in: https://metanorma.github.io/mn-native-pdf/ , and noticed that there are two duplicated OGC docs: *Technical Committee Policies and Procedures (version 26)* and *Conformance Test Guidelines for OpenGIS Catalog Services Specification for CORBA (00-027)*

**Comment by anermina** [comment]
@manuel489 and I agreed on splitting the work. Below are my comments for OGC 05-020r27.

OGC 05-020r27 - native PDF vs. generated DOC
-------------------
- Header is different on the front page.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77473368-a9c74980-6e15-11ea-9f2e-1b6d701036ed.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77473401-b481de80-6e15-11ea-8998-f8a23f858a6f.png)

- Header on the other pages includes year in PDF, unlike in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77473491-daa77e80-6e15-11ea-977e-e6f52fdb8ec7.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77473526-e7c46d80-6e15-11ea-8814-65432ee50cb3.png)

- Footer differs for even pages (PDF has different footer content on odd and even pages).

PDF:
![image](https://user-images.githubusercontent.com/55683568/77473726-29551880-6e16-11ea-9df4-7c3251bfef46.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77473749-31ad5380-6e16-11ea-92f0-771305ebd328.png)

- In ToC, there are no sections before Abstract in PDF, while they are added in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77473807-4984d780-6e16-11ea-9ead-a7778a374d9c.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77473838-573a5d00-6e16-11ea-93bb-39eae70a83a6.png)

- Heading of tables (e.g. Table A.1 in Annex A) repeats on page breaks in generated DOC, unlike in PDF.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77473931-8355de00-6e16-11ea-9f4f-106b5b1cb9f8.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77473960-92d52700-6e16-11ea-96c4-8295df1bd3bb.png)

- In both PDF and DOC, some references are written only formally. There is actually no References/Bibliography section in this document at all. These references are therefore not written as real cross-references in .adoc and generally don't lead to any position in documents, or to any external link. This applies for example to [ISO 19101, ISO 19106] and [ISO 19109], as shown in the image below. @ronaldtse, can you please let me know whether References/Bibliography section should be added here and if these references are then supposed to be added and referenced properly?

![image](https://user-images.githubusercontent.com/55683568/77474297-273f8980-6e17-11ea-9a3a-6595855f66f9.png)

**Comment by anermina** [comment]
OGC 10-100r3
-------------------
- The same comments for header and footer as in OGC 05-020r27 apply here as well. The only difference from OGC 05-020r27 is that even pages in PDF have "© 2012 CubeWerx Inc." in footer.

PDF (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77537320-2867c980-6e9e-11ea-93f2-68f73848f281.png)

DOC (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77537331-30c00480-6e9e-11ea-8b61-f363a71d1ba7.png)

PDF (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77537368-433a3e00-6e9e-11ea-9eeb-38445d58c1ed.png)

DOC (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77537401-5220f080-6e9e-11ea-97a6-2122d1579208.png)

PDF (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77537239-08d0a100-6e9e-11ea-9dec-dbc4198468c6.png)

DOC (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77537272-16862680-6e9e-11ea-9f90-bd540e8b7865.png)

- ToC contains more sections in DOC than in PDF (before the Scope). This is the same kind of difference as in OGC 05-020r27, but in this PDF some preface sections are really missing. Therefore, difference in ToC is probably only in sections before the Preface.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77537467-741a7300-6e9e-11ea-9ddd-acb57b161b84.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77537623-b2b02d80-6e9e-11ea-869c-692779878c21.png)

- Preface section is unnumbered in PDF, while it is numbered with "i." in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77537672-c196e000-6e9e-11ea-94e8-fea9e5cc4f40.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77537707-cb204800-6e9e-11ea-868d-0fdbed7ecc46.png)

- Some preface sections are missing in PDF:
	- iii. Document terms and definitions
	- iv. Document contributor contact points
	- v. Changes to the OpenGIS® Abstract Specification
	- vi. Changes to existing Implementation Standards
	- vii. Future work
	- viii. Foreword
	- ix. Introduction

- Column widths are adjusted differently in PDF and DOC. In this specific case, everything seems fine, but I'm not sure whether this could be a problem in some other cases where tables would unnecessarily be too long because some column (as the first one in PDF) is much wider than it really needs to be.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77537802-facf5000-6e9e-11ea-9493-9689fac5e7a0.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77537831-091d6c00-6e9f-11ea-9928-22a528065dcf.png)

This can also be seen in Table 5.

- Capital R is used in PDF for "3. Normative References", while DOC uses small r - "3. Normative references".

PDF:
![image](https://user-images.githubusercontent.com/55683568/77537909-25210d80-6e9f-11ea-8c5d-d1d9732ad2bf.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77537889-1e929600-6e9f-11ea-9bbb-0b20af8da5f1.png)

- PDF contains more detailed description of OGC references than DOC. If any changes are required in .adoc, please let me know.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77537956-34a05680-6e9f-11ea-9ae0-a8e9326c3ba7.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77537969-3c5ffb00-6e9f-11ea-8026-44cb1bd32fb0.png)

- "Recommended Reading" text is not available in PDF in Normative references section. 

PDF:
![image](https://user-images.githubusercontent.com/55683568/77538004-4bdf4400-6e9f-11ea-8c3b-cfef1f8592a6.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77538022-54377f00-6e9f-11ea-90cf-69ceacdd9d9f.png)

- Table from Normative references section is numbered badly in DOC as Table 8 (as the last table).
In PDF, this table doesn't exist since it's the part of "Recommended Reading".

DOC:
![image](https://user-images.githubusercontent.com/55683568/77538394-fb1c1b00-6e9f-11ea-8d39-8600c956bfc9.png)

- Table 3 doesn't have any content in the last column in DOC. I'm not sure why monospace makes troubles in this case.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77539692-1425cb80-6ea2-11ea-855d-dd1c139a757b.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77539735-2273e780-6ea2-11ea-9ec6-9df9d75807fb.png)

- Figure 1 is too big in PDF (resolution is not good and therefore this size looks bad).

PDF:
![image](https://user-images.githubusercontent.com/55683568/77538457-1555f900-6ea0-11ea-82f0-58daea4501fd.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77538500-2272e800-6ea0-11ea-87af-f9734a3b0873.png)

- Style of the 5th numbering level differs. PDF uses 1), 2), 3), etc., while DOC uses I), II), III), etc.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77538639-52ba8680-6ea0-11ea-8e8f-a885a2343061.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77538678-6239cf80-6ea0-11ea-8f9a-d5607b9cfa18.png)

- Cross-references for tables slightly differ. In PDF, dash is used, e.g. "Table C-1", while dot is used in DOC, e.g. "Table C.1".

PDF:
![image](https://user-images.githubusercontent.com/55683568/77538737-82698e80-6ea0-11ea-94f3-e4e2d61a8ca9.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77538781-93b29b00-6ea0-11ea-9ec7-71a130f04473.png)

**Comment by manuel489** [comment]
## OGC-00-027 -- OGC Conformance Test Guidelines for OpenGIS Catalog Services Specification for CORBA 

### Visual diffs

- The header text in PDF version is "Open Geospatial Consortium 00-027:2020" while in doc version is "Open Geospatial Consortium 00-027"

- In the table of contents:
  - some entries are missing in PDF version in comparison with doc version. (These are indicated in red squares down below.)
  - the entry 4.2 is bad rendered in PDF version in comparison with doc version.

PDF:
![pdf-capture1](https://user-images.githubusercontent.com/33627611/77596033-3e42b200-6ed1-11ea-87f3-6cbbd010548c.PNG)

DOC:
![doc-capture1](https://user-images.githubusercontent.com/33627611/77596043-40a50c00-6ed1-11ea-8f5b-44e43057b299.PNG)
 
- The preface sections, "Submission Contact Points", "Editors" and "Document Conventions" are missing in PDF version.

- In annex section:
  - the title in PDF version is shown as "Annex", while in doc version, it is shown as "Annex A"
  - there is no caption for the code block in PDF version (only a "-1" text is shown), unlike doc version, which shows the caption "Figure A.1".

**Comment by manuel489** [comment]
## 08-062r7 - OGC OGC Reference Model
### Visual diffs

- In PDF version, the header text is "© Open Geospatial Consortium 2020 – All rights reserved", while in doc version is "Open Geospatial Consortium 08-062r7"
- Regarding the table of contents, the entries "Copyright notice", "License Agreement", "Warning", and "Introduction" are missing in PDF version. 
- The PDF version does not contain the "Introduction" preface section.
- The footer in even pages is "© 2020 OGC" in PDF version and "© Open Geospatial Consortium 2020 – All rights reserved" in doc version.
- The images in doc version look smaller than PDF version (in general).

**Comment by manuel489** [comment]
## 17-069 - OGC Web Feature Service 3.0: Part 1 - Core
### Visual diffs

- The header text in PDF version is "Open Geospatial Consortium 17-069:2020", while in doc version is "Open Geospatial Consortium 17-069"
- In the table of contents:
  - the entries: "Copyright notice", "License Agreement" and "Warning for Drafts" are missing in PDF version, unlike doc version.
  - the "Preface" entry is shown without section numbering ("iii.") in PDF version, unlike doc version.

PDF:
![pdf-capture2](https://user-images.githubusercontent.com/33627611/77597156-52d47980-6ed4-11ea-9755-860c25fc2f84.PNG)

DOC:
![doc-capture2](https://user-images.githubusercontent.com/33627611/77597159-5405a680-6ed4-11ea-8d32-00a36dac1434.PNG)

- The "Preface" section doesn't have a section number ("iii.") in PDF version.

- In the section 4, "Terms and definitions": 
	- the section numbers and titles are line separated in PDF version.
	- the first note block is rendered as "???" in doc version.

PDF:
![pdf-capture3](https://user-images.githubusercontent.com/33627611/77597343-f6258e80-6ed4-11ea-9940-e49c71eb5542.PNG)

DOC:
![doc-capture3](https://user-images.githubusercontent.com/33627611/77597344-f887e880-6ed4-11ea-9482-30e040e48c99.PNG)

- In doc version, example block titles are duplicated. (I believe this problem is solved already in the latest version of metanorma-ogc)
For example:
![bug-capture](https://user-images.githubusercontent.com/33627611/77597518-8532a680-6ed5-11ea-99ef-c6b219ead58a.PNG)

**Comment by manuel489** [comment]
## 18-016r1 - OGC CDB Version 1.1 Release Notes
### Visual diffs
- In table of contents: 
  - the entries "Copyright notice", "License Agreement" and "Warning for Drafts" are missing in PDF version, unlike doc version.
  - the "Preface" entry is shown without section numbering ("iii.") in PDF version, unlike doc version.

- The "Preface" section doesn't have a section number ("iii.") in PDF version.

PDF:
![pdf-capture4](https://user-images.githubusercontent.com/33627611/77597855-80babd80-6ed6-11ea-9750-677beacbd223.PNG)

DOC:
![doc-capture4](https://user-images.githubusercontent.com/33627611/77597860-844e4480-6ed6-11ea-95dc-b1a27241f4f4.PNG)

**Comment by manuel489** [comment]
## 18-046 - OGC Earth Observation Exploitation Platform Hackathon 2018 Engineering Report
### Visual diffs
- The header text in PDF version is "Open Geospatial Consortium 18-046:2020", while in doc version is "Open Geospatial Consortium 18-046".
- The footer text, in even pages, is "© 2020 OGC" for PDF version, and "© Open Geospatial Consortium 2020 – All rights reserved" for doc version.
- In table of contents, the entries "Copyright notice", "License Agreement" and "Warning for Drafts" are missing in PDF version, unlike doc version.
- "Summary" section is missing in PDF version.

**Comment by anermina** [comment]
OGC 18-053r2
--------------------
Same/similar differences as in previous documents:
- The same comments for header and footer as in OGC 05-020r27 apply here as well. 

PDF (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77631050-57d50f80-6f4c-11ea-997f-4e031bce4536.png)

DOC (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77631076-60c5e100-6f4c-11ea-92c7-332a70f87139.png)

PDF (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77631112-6e7b6680-6f4c-11ea-829e-b68c054158c3.png)

DOC (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77631154-79ce9200-6f4c-11ea-9757-4bd2a5b08881.png)

PDF (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77631215-8bb03500-6f4c-11ea-8a21-3303de844342.png)

DOC (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77631231-923eac80-6f4c-11ea-86ae-aaf955bc0669.png)

- ToC contains more sections in DOC than in PDF (before the Scope). 

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631259-9e2a6e80-6f4c-11ea-93d3-89f5d4465102.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631286-a682a980-6f4c-11ea-8930-cf691c52732d.png)

- Preface is unnumbered in PDF, while it's numbered with "i." in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631327-b4382f00-6f4c-11ea-84a5-4448cecca8ab.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631343-b9957980-6f4c-11ea-858b-803fc2b250f9.png)

- PDF doesn't have the following preface sections:
	ii. Source of the content for this OGC document
	iii. Validity of content
	iv. Future work

- Some figures are too big in PDF (e.g. Figure 13). Some of them are too small (Figure 20).

PDF:
![image](https://user-images.githubusercontent.com/55683568/77632082-c6669d00-6f4d-11ea-953d-8e37ded38314.png)
![image](https://user-images.githubusercontent.com/55683568/77632290-134a7380-6f4e-11ea-8b0d-dbb6b91e22b5.png)

- Heading in tables (e.g. table in section 7.7) repeats on page breaks in generated DOC, unlike in PDF.

New issues:
- License Agreement lacks the last paragraph in DOC (which has a different font style than the rest of the paragraphs here). That paragraph is added after List of Figures in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631412-d5008480-6f4c-11ea-8b69-1539cc16e13d.png)

DOC (Licence Agreement section):
![image](https://user-images.githubusercontent.com/55683568/77631572-0a0cd700-6f4d-11ea-96ab-f88e2318869d.png)

DOC (List of Figures section):
![image](https://user-images.githubusercontent.com/55683568/77631626-1c871080-6f4d-11ea-89ba-5e3b9e3f7269.png)

- Terms in "Terms and definitions" section are written below the number in PDF, while they are written next to the number in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631658-2b6dc300-6f4d-11ea-9289-e6131ca606a2.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631677-33c5fe00-6f4d-11ea-8846-5f9f4e23ae82.png)

- Page break is added between the title and subtitle in "References" section in PDF.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631723-44767400-6f4d-11ea-8bca-160609923d42.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631743-4c361880-6f4d-11ea-8284-87b9ce2d39b7.png)

- "Normative" subsection of "References" section is unnumbered in PDF and numbered in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631772-57894400-6f4d-11ea-9e00-c18a8516f372.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631788-5e17bb80-6f4d-11ea-91aa-07072903de5c.png)

- Document numbers of IETF references are duplicated in PDF. 

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631861-77206c80-6f4d-11ea-962b-5db6468024b2.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631893-830c2e80-6f4d-11ea-9fd6-094925cb3071.png)

- OGC reference description differs in PDF and DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77631971-a0d99380-6f4d-11ea-9fb3-ee984114c6e9.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77631993-a7680b00-6f4d-11ea-94dc-2e205d750ada.png)

- Some parts of the text go out of the table borders in table from section 7.7., in PDF.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77632128-db433080-6f4d-11ea-9332-74694de3e4de.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77632175-eb5b1000-6f4d-11ea-8751-e7670aeaabcd.png)

Additionally:
- Minor changes in .adoc are made in https://github.com/metanorma/mn-samples-ogc/pull/71.

**Comment by anermina** [comment]
OGC 16-080
-------------------------------
Same/similar differences as in previous documents:

- The same comments for header and footer as in OGC 05-020r27 apply here as well. 

PDF (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77635920-9c17de00-6f53-11ea-9c8e-c1b277ec08fd.png)

DOC (header, front page):
![image](https://user-images.githubusercontent.com/55683568/77635947-a2a65580-6f53-11ea-97f6-9ab77af45e3c.png)

PDF (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77636014-bbaf0680-6f53-11ea-871d-d66ea96ce416.png)

DOC (header, other pages):
![image](https://user-images.githubusercontent.com/55683568/77636025-c23d7e00-6f53-11ea-9708-f4717cbb791c.png)

PDF (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77636066-d2edf400-6f53-11ea-93ca-db6b12c660e4.png)

DOC (footer, even pages):
![image](https://user-images.githubusercontent.com/55683568/77636078-d84b3e80-6f53-11ea-8627-46d180c68e77.png)

- ToC contains more sections in DOC than in PDF (sections before Normative references).

PDF:
![image](https://user-images.githubusercontent.com/55683568/77636119-e7ca8780-6f53-11ea-9abe-38a829c24a52.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77636146-f022c280-6f53-11ea-8638-c51b5172f3a4.png)

- Preface sections are missing in PDF:
	i. Introduction
	i.1. Usage Example — Shared Situational Awareness
	i.2. Usage Example — Sharing Catalogue Searches
	i.3. Usage Example — Processing Services Management
	i.4. Usage Example — Index or Catalogue of Data Collections
	i.5. Benefits of OWS Context Documents 

- OGC references descriptions differ in PDF and DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/77636209-06c91980-6f54-11ea-8b4a-4fbed520724f.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/77636228-0df02780-6f54-11ea-8ee4-63cab2d83152.png)

Additionally:
- Minor changes in .adoc are made in https://github.com/metanorma/mn-samples-ogc/pull/72.

**Comment by anermina** [comment]
As @manuel489 mentioned, for OGC 05-020r26 we have PDF available, but not DOC. However, we have r27 of this document as DOC (and the same release as PDF, so these were compared). Below is the list of documents that were matched, and the ones we lack PDFs for.

Documents for which we have both PDF and DOC versions:
- 00-027
- 05-020r27
- 10-100r3
- 18-053r2
- 16-080
- 08-062r7
- 17-069r3
- 18-046
- 18-016r1

DOC is available, but PDF isn't for the following:
- 10-091r3
- 12-077r1
- 14-065r2
- 15-104r5
- 15-120r5
- 16-114r3
- 16-131r2
- 19-004

**Comment by ronaldtse** [comment]
@manuel489 I know we have a duplicated (but not identical!) Technical Committee Policies and Procedures (05-020r26 and 05-020r27).

But there's only one 00-027?

**Comment by manuel489** [comment]
> @manuel489 I know we have a duplicated (but not identical!) Technical Committee Policies and Procedures (05-020r26 and 05-020r27).

@ronaldtse , yes I noticed the difference between 05-020r26 and 05-020r27 (which corresponds to version 26.0 and 27.0 respectively, right?), but it seems like there are two docs with the 05-020r26 id.

> But there's only one 00-027?

Well, I noticed two docs with the 00-027 id, these are: "00-027" and "Conformance Test Guidelines for OpenGIS Catalog Services Specification for CORBA"

I attach an image where a indicate these "duplicated" docs in red square:
![Capture](https://user-images.githubusercontent.com/33627611/77754471-c88a3380-7001-11ea-9bba-53db31e5b466.PNG)

**Comment by manuel489** [comment]
New issues/diffs found:

* [DOC vs PDF: Preface content is not showing up in PDF version](https://github.com/metanorma/metanorma-ogc/issues/170)
* [Images are not showing up in DOC version](https://github.com/metanorma/metanorma-ogc/issues/169)
* [DOC vs PDF: Page numbering is missing in DOC version](https://github.com/metanorma/metanorma-ogc/issues/168)
* [DOC vs PDF: Short horizontal spacing in Sections/Subsections](https://github.com/metanorma/metanorma-ogc/issues/167)
* [DOC vs PDF: Large horizontal spacing in Note block](https://github.com/metanorma/metanorma-ogc/issues/166)
* [DOC vs PDF: Example title alignment](https://github.com/metanorma/metanorma-ogc/issues/165)
* [DOC vs PDF: "Normative references" title is misspelled in PDF](https://github.com/metanorma/metanorma-ogc/issues/164)
* [DOC vs PDF: Preface title is not numbered](https://github.com/metanorma/metanorma-ogc/issues/163)
* [DOC vs PDF: Document metadata list differs](https://github.com/metanorma/metanorma-ogc/issues/162)
* [Copyright notice text alignment](https://github.com/metanorma/metanorma-ogc/issues/161)
* [Error message raising up on DOC file opening](https://github.com/metanorma/metanorma-ogc/issues/160)
* ["No access to online site" when fetching OGC references](https://github.com/relaton/relaton-ogc/issues/11)

**Comment by manuel489** [comment]
Waiting for substantial changes in all flavors to resume this review again. This ticket remains on hold until then.

**Comment by manuel489** [comment]
The big changes has already been made. The review is resumed.

**Comment by manuel489** [comment]
All OGC documents have been reviewed.
Two minor issues left. Already reported in separate tickets.
Closing.
