### ISSUE TITLE
UN: Update Plenary layout

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#90]
The correct layouts for 'plenary' documents are:

* https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/11E%20ECE_TRACE_C_CEFACT_2019_26.pdf
* https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/11E%20ECE_TRADE_C_CEFACT_2019_09%20WP%20Blockchain%20Overview.pdf
* https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_C_CEFACT_2018_1E.pdf
* https://github.com/metanorma/mn-samples-un/blob/master/reference-docs/ECE_TRADE_C_CEFACT_2018_6E.pdf

The XSLT layout to edit is `xslt_src/unece.plenary.xsl`.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

One issue:

Original:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11865/77493960-728d8280-6e7f-11ea-9e26-766a2bf10ad9.png">

Generated:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11865/77493966-77eacd00-6e7f-11ea-8baa-d8f69f06ade3.png">

**Comment by Intelligent2013** [comment]
@ronaldtse Sources XML don't have a title. For example, in https://metanorma.github.io/mn-samples-un/documents/ECE_TRADE_C_CEFACT_2018_6E.xml there isn't 'Paperless Trade White Paper' text.

And how can I obtain a text 'Item 6 of the provisional agenda' from XML?
![image](https://user-images.githubusercontent.com/5559926/77679534-b679a800-6fa3-11ea-9e2f-572a3decf765.png)

**Comment by opoudjis** [comment]
"Item 6 of the provisional agenda"

This is partly markup that hasn't been proofread by me, and partly me not implementing what is displayed, because I did not have assurance about how generally applicable it is:

The number 6 is meant to be in //bibdata/ext/session/item-number.  I'm seeing it hasn't been marked up that way. And I rendered it as "Agenda Item {{ session_itemnumber[0] }}", because I had no assurance that all agendas are provisional: recall that we had very incomplete information from UN (and needless to say, I simply have not had the time to go through the UN's documentation for them).

The text for "Item xx of the ??" will need to be internationalised as well; since the XSLTs lack the internationalisation capability of the isodoc gem, I would have to add a field for this in bibdata/ext in future. But since we still haven't worked out what actually goes in there, put in "Agenda Item {{ //bibdata/ext/session/item-number }}" for now.

Missing title:

That's also a markup error: the gem requires a title attribute, and does not parse the Asciidoctor title if the title attribute is absent, as has been done in markup. I will loosen that condition up in the gem now.

**Comment by opoudjis** [comment]
More generally, obviously the UN documents need proofreading and enhancements to the gem, and we need input from the UNECE team.

**Comment by Intelligent2013** [comment]
@opoudjis thank you for the comment.

@ronaldtse The title pages contain a barcode like this:
![image](https://user-images.githubusercontent.com/5559926/77767957-e03dd800-7052-11ea-8ba4-0f2e34ecb616.png)

Do you need it in PDF?

**Comment by ronaldtse** [comment]
@Intelligent2013 The document number of "GE.18-01763(E)" is assigned by the UNDoc system on submission. It would be great if we can generate the barcode, but is not a killer if we can't.

I know we can, but depends on how much time we need to get that?

**Comment by ronaldtse** [comment]
@Intelligent2013 has implemented barcode + QR code and is now fixing CI. Once done please close this ticket. Thanks!

**Comment by Intelligent2013** [comment]
XSL un.plenary.core.xsl can't cover all Plenary layouts. For example:
- ECE_TRADE_C_CEFACT_2018_1E.pdf: document body starts on first page;
- some documents has a different section numeration.

**Comment by Intelligent2013** [comment]
UN resulted PDFs have QRCode and barcodes:
https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/un-ECE_TRADE_C_CEFACT_2019_26.pdf
https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/un-ECE_TRADE_C_CEFACT_2019_09.pdf
https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/un-ECE_TRADE_C_CEFACT_2018_6E.pdf
https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/un-ECE_TRADE_C_CEFACT_2018_1E.pdf
